version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # Specify Python version if needed
    commands:
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt -t python
      - echo "Zipping dependencies into layer.zip..."
      - zip -q -r terraform/layer.zip python
      - rm -rf python  # Clean up to avoid clutter

  pre_build:
    commands:
      - echo "Pre-build steps completed"

  build:
    commands:
      - echo "Initializing Terraform..."
      - cd terraform  # Your existing Terraform code directory
      - terraform init
      - terraform plan
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Build process completed!"
